[project]
name = "orbit"
version = "1.1.1"
description = "Supervised Machine-Learning Phenotyping for multiplex pathology images."
readme = "README.md"
authors = [{name = "Michael Fotheringham"}]
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "joblib",
    "tifffile",
    "scikit-image",
    "matplotlib",
    "napari",
    "qtpy",
    "pyside6",
    "qptifffile",
]

[project.scripts]
orbit = "orbit.app:main"

[build-system]
requires = ["uv_build>=0.12"]
build-backend = "uv_build"